cherryusb_incs = include_directories(
  'core',
  'common',
  # 'class/aoa',
  # 'class/audio',
  'class/video',
  # 'class/vendor',
  # 'class/vendor/wifi',
  # 'class/vendor/serial',
  # 'class/vendor/xbox',
  # 'class/vendor/net',
  'class/cdc',
  # 'class/wireless',
  # 'class/adb',
  # 'class/msc',
  # 'class/hid',
  'class/hub',
  # 'class/midi',
  # 'class/dfu',
  # 'class/mtp',
  'port/dwc2',
)

cherryusb_srcs = files(
  # 'class/adb/usbd_adb.c',
  # 'class/aoa/usbh_aoa.c',
  # 'class/audio/usbd_audio.c',
  # 'class/audio/usbh_audio.c',
  'class/cdc/usbd_cdc_acm.c',
  # 'class/cdc/usbd_cdc_ecm.c',
  # 'class/cdc/usbh_cdc_acm.c',
  # 'class/cdc/usbh_cdc_ecm.c',
  # 'class/cdc/usbh_cdc_ncm.c',
  # 'class/dfu/usbd_dfu.c',
  # 'class/hid/usbd_hid.c',
  # 'class/hid/usbh_hid.c',
  # 'class/hub/usbh_hub.c',
  # 'class/msc/usbd_msc.c',
  # 'class/msc/usbh_msc.c',
  # 'class/template/usbd_xxx.c',
  # 'class/template/usbh_xxx.c',
  # 'class/vendor/net/usbh_asix.c',
  # 'class/vendor/net/usbh_rtl8152.c',
  # 'class/vendor/serial/usbh_ch34x.c',
  # 'class/vendor/serial/usbh_cp210x.c',
  # 'class/vendor/serial/usbh_ftdi.c',
  # 'class/vendor/serial/usbh_pl2303.c',
  # 'class/vendor/wifi/usbh_bl616.c',
  # 'class/vendor/xbox/usbh_xbox.c',
  'class/video/usbd_video.c',
  # 'class/video/usbh_video.c',
  # 'class/wireless/usbd_rndis.c',
  # 'class/wireless/usbh_bluetooth.c',
  # 'class/wireless/usbh_rndis.c',
  'core/usbd_core.c',
  # 'core/usbh_core.c',
  # 'core/usbotg_core.c',
  'port/dwc2/usb_dc_dwc2.c',
  'port/dwc2/usb_glue_st.c',
  # 'port/dwc2/usb_hc_dwc2.c',
)