option('TARGET_PLATFORM',
  type: 'string',
  value: 'stm32l4xx',
  description: 'Target platform name')

option('TARGET_USE_LOG',
  type: 'boolean',
  value: true,
  description: 'Enable log')

option('STM32_USB_Host',
  type: 'boolean',
  value: false,
  description: 'Enable USB Host library')

option('STM32_USB_Device',
  type: 'boolean',
  value: false,
  description: 'Enable USB Device library')

option('JLINK_REMOTE',
  type: 'string',
  value: 'disabled',
  description: 'Enable JLink remote debug')