//$file${.::uvc.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: uvc.qm
// File:  ${.::uvc.c}
//
// This code has been generated by QM 7.0.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::uvc.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpc.h"
#include "bsp.h"
#include "uvc.h"
#include "led.h"
#include "camera.h"
#include "st7789.h"

//$declare${AOs::UVC} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::UVC} ................................................................
typedef struct UVC {
// protected:
    QActive super;

// private:
    QTimeEvt timeEvt;

// public:
    QTimeEvt healthEvt;
} UVC;

extern UVC UVC_inst;

// protected:
static QState UVC_initial(UVC * const me, void const * const par);
static QState UVC_normal(UVC * const me, QEvt const * const e);
//$enddecl${AOs::UVC} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::AO_UVC} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::AO_UVC} .............................................................
QActive * const AO_UVC = &UVC_inst.super;
//$enddef${AOs::AO_UVC} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::UVC_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::UVC_ctor} ...........................................................
void UVC_ctor(void) {
    UVC * const me = &UVC_inst;
    QActive_ctor(&me->super, Q_STATE_CAST(&UVC_initial));
    QTimeEvt_ctorX(&me->timeEvt, &me->super, TIMEOUT_SIG, 0U);
    QTimeEvt_ctorX(&me->healthEvt, &me->super, UVC_HEALTH_SIG, 0U);
}
//$enddef${AOs::UVC_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::UVC} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::UVC} ................................................................
UVC UVC_inst;

//${AOs::UVC::SM} ............................................................
static QState UVC_initial(UVC * const me, void const * const par) {
    //${AOs::UVC::SM::initial}
    (void)par; // unused parameter
    camera_start((uint32_t)camera_buffer, sizeof(camera_buffer), 1);
    //QTimeEvt_armX(&me->healthEvt, BSP_TICKS_PER_SEC/2, BSP_TICKS_PER_SEC/2);

    QS_FUN_DICTIONARY(&UVC_normal);

    return Q_TRAN(&UVC_normal);
}

//${AOs::UVC::SM::normal} ....................................................
static QState UVC_normal(UVC * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::UVC::SM::normal::UVC_HEALTH}
        case UVC_HEALTH_SIG: {
            led_toggle(LED_1);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::UVC::SM::normal::UVC_FRAME}
        case UVC_FRAME_SIG: {
            st7789_draw_image(0, 0, 240, 320, (uint16_t*)camera_buffer);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::UVC::SM::normal::UVC_PFC}
        case UVC_PFC_SIG: {
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
//$enddef${AOs::UVC} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
