# Driver source files provided by the user
drivers_sources = files(
  'drv_common.c',
#   'drv_dac.c',
#   'drv_wdt.c',
  'drv_usart.c',
#   'drv_eth.c',
#   'drv_usbd.c',
#   'drv_nand.c',
#   'drv_hard_i2c.c',
#   'drv_soft_i2c.c',
#   'drv_lcd.c',
  'drv_gpio.c',
#   'drv_sdmmc.c',
#   'drv_flash_l4.c',
#   'drv_lcd_mipi.c',
  'drv_pm.c',
  'drv_rtc.c',
#   'drv_soft_spi.c',
#   'drv_spi.c',
#   'drv_adc.c',
  'board.c',
#   'drv_crypto.c',
#   'drv_pulse_encoder.c',
  'drv_lptim.c',
#   'drv_qspi.c',
#   'drv_tim.c',
#   'drv_sdram.c',
#   'drv_sdio.c',
#   'drv_usart_v2.c',
#   'drv_can.c',
#   'drv_pwm.c',
#   'drv_usbh.c'
)

drivers_incdirs = include_directories(
  '.',
  'config'
)
